print_model <- function(sm, t){
  print(sprintf("The model at time t = %d is:  ", t))
  print(sprintf("     --------         --------"))
  print(sprintf("     |%06s|         |%06s|", strtrim(sm[4, t+1],6), strtrim(sm[5, t+1],6)))
  print(sprintf("     |------|=========|------|"))
  print(sprintf("     |%06s|         |%06s|", strtrim(sm[9, t+1],6), strtrim(sm[10, t+1],6)))
  print(sprintf("     --------         --------"))
  print(sprintf("       //                ||   "))
  print(sprintf("      //          ^  ^   ||   "))
  print(sprintf("     //         ^   ^    ||   "))
  print(sprintf("    //        ^   ^  ^   ||   "))
  print(sprintf("   //          ^  ^   ^  ||   "))
  print(sprintf("--------     ^    ^  ^   ||   "))
  print(sprintf("|%06s|       ^  ^   ^  ||   ", strtrim(sm[2, t+1],6)))
  print(sprintf("|------|    ^  ^   ^     ||   "))
  print(sprintf("|%06s|     ^   ^  ^    ||   ", strtrim(sm[7, t+1],6)))
  print(sprintf("--------   ^   ^   ^     ||   "))
  print(sprintf("   ||         ^  ^       ||   "))
  print(sprintf("   ||       ^   ^        ||   "))
  print(sprintf("   ||         ^          ||   "))
  print(sprintf("   ||      ^   ^         ||   "))
  print(sprintf("   ||         ^          ||   "))
  print(sprintf("--------              --------"))
  print(sprintf("|%06s|              |%06s|", strtrim(sm[1, t+1],6), strtrim(sm[3, t+1],6)))
  print(sprintf("|------|==============|------|"))
  print(sprintf("|%06s|              |%06s|", strtrim(sm[6, t+1],6), strtrim(sm[7, t+1],6)))
  print(sprintf("--------              --------"))
}
